# Python Function App to Linux on Azure
# Build a Python function app and deploy it to Azure as a Linux function app.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

variables:
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

  # Working Directory
  workingDirectory: '$(System.DefaultWorkingDirectory)/'
  functionAppName: 'jesumeflextestpy'
  resourceGroup: 'consumpttest' 

stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)

    steps:

    - task: UsePythonVersion@0
      displayName: 'Use Python 3.11'
      inputs:
        versionSpec: 3.11 # Functions V2 supports Python 3.6 as of today

    - bash: |
        pip install --target="./.python_packages/lib/site-packages" -r ./requirements.txt
      workingDirectory: $(workingDirectory)
      displayName: 'Install application dependencies'

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(workingDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      artifact: drop
    
    - task: AzureCLI@2
      displayName: 'Deploy to Flex Consumption Function App using /api/publish (remote build)'
      inputs:
        azureSubscription: 'JesumeWIF-v3'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          echo "Deploying to Azure Function App (Flex Consumption) via /api/publish endpoint"
          az functionapp deployment source config-zip \
            --name "$(functionAppName)" \
            --resource-group "$(resourceGroup)" \
            --src "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip" \
            --build-remote true


