name: Build and deploy Python project to Azure Function App - jesumeflextestpy

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.11'
  FUNCTIONAPP_NAME: 'jesumeflextestpy' # your Azure Function App name
  ZIP_PATH: 'functionapp.zip'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4AEA49FEDB31448089DF9AA70FE13446 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_567FE88E50CE45B2823DB6F3CACE52B6 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_03C7A4A070154E4BBBD3B1E205178ED2 }}

      - name: Create deployment zip package
        run: |
          zip -r ${{ env.ZIP_PATH }} . -x "venv/*" "**/__pycache__/*" ".git/*" ".github/*"

      - name: Deploy to Azure Function App with remote build (Flex)
        run: |
          az functionapp deployment source config-zip \
            --name ${{ env.FUNCTIONAPP_NAME }} \
            --resource-group "consumpttest" \
            --src ${{ env.ZIP_PATH }} \
            --build-remote true
