name: Build and deploy Python project to Azure Function App - jesumeflextestpy

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './release.zip' 
  PYTHON_VERSION: '3.11'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and activate virtual environment + install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          mkdir -p .python_packages/lib/site-packages
          pip install --target="./.python_packages/lib/site-packages" -r requirements.txt

      - name: Show installed packages (for debug)
        run: find .python_packages

      - name: Zip code and dependencies into release.zip
        run: |
          zip -r release.zip . -x "venv/*" ".git/*" ".github/*" "release.zip"

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4AEA49FEDB31448089DF9AA70FE13446 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_567FE88E50CE45B2823DB6F3CACE52B6 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_03C7A4A070154E4BBBD3B1E205178ED2 }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: 'jesumeflextestpy'
          slot-name: 'Production'
          package: './release.zip'
